services:
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  backend:
    container_name: backend
    image: abrodep/cloud-storage-backend:latest
    pull_policy: always
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_REDIS_HOST: redis
      SPRING_MINIO_HOST: http://minio:9000
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    environment:
        MINIO_ROOT_USER: user
        MINIO_ROOT_PASSWORD: user123456
  frontend:
    container_name: frontend
    build: frontend/cloud-storage-frontend/.
    ports:
    - '80:80'
    restart: unless-stopped


